//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_NET_FRAMEWORK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<bool> EnStock { get; set; }
        public string Edicion { get; set; }
        public Nullable<int> Id_Categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
